const currencies = [
  { id: 1, symbol: 'USD', value: '97.$', label: 'US Dollar' },
  { id: 2, symbol: 'CAD', value: 'CAD.$', label: 'Canadian Dollar' },
  { id: 3, symbol: 'AUD', value: 'AUD.$', label: 'Australian Dollar' },
  { id: 4, symbol: 'GBP', value: 'GBP.£', label: 'British Pound Sterling' },
  { id: 5, symbol: 'EUR', value: 'EUR.€', label: 'Euro' },
  { id: 6, symbol: 'ALL', value: 'ALL.Lek', label: 'Albanian Lek' },
  { id: 7, symbol: 'AMD', value: 'AMD.֏', label: 'Armenian Dram' },
  { id: 8, symbol: 'AOA', label: 'Angolan Kwanza', value: 'AOA' },
  { id: 9, symbol: 'AZN', value: 'AZN.₼', label: 'Azerbaijani Manat' },
  { id: 10, symbol: 'BSD', value: 'BSD.$', label: 'Bahamian Dollar' },
  { id: 11, symbol: 'BHD', label: 'Bahraini Dinar', value: 'BHD' },
  { id: 12, symbol: 'BDT', value: 'BDT.৳', label: 'Bangladeshi Taka' },
  { id: 13, symbol: 'BBD', value: 'BBD.$', label: 'Barbadian Dollar' },
  { id: 14, symbol: 'BYR', value: 'BYR.Br', label: 'Belarusian Ruble' },
  { id: 15, symbol: 'BEF', label: 'Belgian Franc', value: 'BEF' },
  { id: 16, symbol: 'BZD', value: 'BZD.BZ$', label: 'Belize Dollar' },
  { id: 17, symbol: 'BMD', value: 'BMD.$', label: 'Bermudan Dollar' },
  { id: 18, symbol: 'BTN', value: 'BTN.Nu.', label: 'Bhutanese Ngultrum' },
  { id: 19, symbol: 'BTC', value: 'BTC.฿', label: 'Bitcoin' },
  { id: 20, symbol: 'BOB', label: 'Bolivian Boliviano', value: 'BOB' },
  {
    id: 21,
    symbol: 'BAM',
    value: 'BAM.KM',
    label: 'Bosnia-Herzegovina Convertible Mark',
  },
  { id: 22, symbol: 'BWP', value: 'BWP.P', label: 'Botswanan Pula' },
  { id: 23, symbol: 'BRL', value: 'BRL.R$', label: 'Brazilian Real' },
  { id: 24, symbol: 'AWG', value: 'AWG.ƒ', label: 'Aruban Florin' },
  { id: 25, symbol: 'BND', value: 'BND.$', label: 'Brunei Dollar' },
  { id: 26, symbol: 'BGN', value: 'BGN.лв', label: 'Bulgarian Lev' },
  { id: 27, symbol: 'BIF', label: 'Burundian Franc', value: 'BIF' },
  { id: 28, symbol: 'KHR', value: 'KHR.៛', label: 'Cambodian Riel' },
  { id: 29, symbol: 'DZD', label: 'Algerian Dinar', value: 'DZD' },
  { id: 30, symbol: 'CVE', label: 'Cape Verdean Escudo', value: 'CVE' },
  { id: 31, symbol: 'KYD', value: 'KYD.$', label: 'Cayman Islands Dollar' },
  { id: 32, symbol: 'XOF', label: 'CFA Franc BCEAO', value: 'XOF' },
  { id: 33, symbol: 'XAF', label: 'CFA Franc BEAC', value: 'XAF' },
  { id: 34, symbol: 'XPF', label: 'CFP Franc', value: 'XPF' },
  { id: 35, symbol: 'CLP', value: 'CLP.$', label: 'Chilean Peso' },
  { id: 36, symbol: 'CNY', value: 'CNY.¥', label: 'Chinese Yuan' },
  { id: 37, symbol: 'COP', value: 'COP.$', label: 'Colombian Peso' },
  { id: 38, symbol: 'KMF', label: 'Comorian Franc', value: 'KMF' },
  { id: 39, symbol: 'CDF', label: 'Congolese Franc', value: 'CDF' },
  { id: 40, symbol: 'CRC', value: 'CRC.₡', label: 'Costa Rican ColÃ³n' },
  { id: 41, symbol: 'HRK', value: 'HRK.kn', label: 'Croatian Kuna' },
  { id: 42, symbol: 'CUC', value: 'CUC.₱', label: 'Cuban Convertible Peso' },
  { id: 43, symbol: 'CZK', value: 'CZK.Kč', label: 'Czech Republic Koruna' },
  { id: 44, symbol: 'DKK', value: 'DKK.kr', label: 'Danish Krone' },
  { id: 45, symbol: 'DJF', label: 'Djiboutian Franc', value: 'DJF' },
  { id: 46, symbol: 'DOP', value: 'DOP.RD$', label: 'Dominican Peso' },
  { id: 47, symbol: 'XCD', value: 'XCD.$', label: 'East Caribbean Dollar' },
  { id: 48, symbol: 'EGP', value: 'EGP.£', label: 'Egyptian Pound' },
  { id: 49, symbol: 'ERN', label: 'Eritrean Nakfa', value: 'ERN' },
  { id: 50, symbol: 'EEK', label: 'Estonian Kroon', value: 'EEK' },
  { id: 51, symbol: 'ETB', label: 'Ethiopian Birr', value: 'ETB' },
  { id: 52, symbol: 'ARS', value: 'ARS.$', label: 'Argentine Peso' },
  { id: 53, symbol: 'FKP', value: 'FKP.£', label: 'Falkland Islands Pound' },
  { id: 54, symbol: 'FJD', value: 'FJD.$', label: 'Fijian Dollar' },
  { id: 55, symbol: 'GMD', label: 'Gambian Dalasi', value: 'GMD' },
  { id: 56, symbol: 'GEL', label: 'Georgianlari', value: 'GEL' },
  { id: 57, symbol: 'DEM', label: 'German Mark', value: 'DEM' },
  { id: 58, symbol: 'GHS', value: 'GHS.¢', label: 'Ghanaian Cedi' },
  { id: 59, symbol: 'GIP', value: 'GIP.£', label: 'Gibraltar Pound' },
  { id: 60, symbol: 'GRD', label: 'Greek Drachma', value: 'GRD' },
  { id: 61, symbol: 'GTQ', value: 'GTQ.Q', label: 'Guatemalan Quetzal' },
  { id: 62, symbol: 'GNF', label: 'Guinean Franc', value: 'GNF' },
  { id: 63, symbol: 'GYD', value: 'GYD.$', label: 'Guyanaese Dollar' },
  { id: 64, symbol: 'HTG', label: 'Haitian Gourde', value: 'HTG' },
  { id: 65, symbol: 'HNL', value: 'HNL.L', label: 'Honduran Lempira' },
  { id: 66, symbol: 'HKD', value: 'HKD.$', label: 'Hong Kong Dollar' },
  { id: 67, symbol: 'HUF', value: 'HUF.Ft', label: 'Hungarian Forint' },
  { id: 68, symbol: 'ISK', value: 'ISK.kr', label: 'Icelandic KrÃ³na' },
  { id: 69, symbol: 'INR', value: 'INR.₹', label: 'Indian Rupee' },
  { id: 70, symbol: 'IDR', value: 'IDR.Rp', label: 'Indonesian Rupiah' },
  { id: 71, symbol: 'IRR', label: 'Iranian Rial', value: 'IRR' },
  { id: 72, symbol: 'IQD', label: 'Iraqi Dinar', value: 'IQD' },
  { id: 73, symbol: 'ILS', value: 'ILS.₪', label: 'Israeli New Sheqel' },
  { id: 74, symbol: 'ITL', label: 'Italian Lira', value: 'ITL' },
  { id: 75, symbol: 'JMD', value: 'JMD.J$', label: 'Jamaican Dollar' },
  { id: 76, symbol: 'JPY', value: 'JPY.¥', label: 'Japanese Yen' },
  { id: 77, symbol: 'JOD', label: 'Jordanian Dinar', value: 'JOD' },
  { id: 78, symbol: 'KZT', value: 'KZT.лв', label: 'Kazakhstani Tenge' },
  { id: 79, symbol: 'KES', label: 'Kenyan Shilling', value: 'KES' },
  { id: 80, symbol: 'KWD', label: 'Kuwaiti Dinar', value: 'KWD' },
  { id: 81, symbol: 'KGS', value: 'KGS.лв', label: 'Kyrgystani Som' },
  { id: 82, symbol: 'laK', value: 'laK.₭', label: 'laotian Kip' },
  { id: 83, symbol: 'LVL', label: 'latvianlats', value: 'LVL' },
  { id: 84, symbol: 'LBP', value: 'LBP.£', label: 'Lebanese Pound' },
  { id: 85, symbol: 'LSL', label: 'Lesotho Loti', value: 'LSL' },
  { id: 86, symbol: 'LRD', value: 'LRD.$', label: 'Liberian Dollar' },
  { id: 87, symbol: 'LYD', label: 'Libyan Dinar', value: 'LYD' },
  { id: 88, symbol: 'LTL', label: 'Lithuanian Litas', value: 'LTL' },
  { id: 89, symbol: 'MOP', label: 'Macanese Pataca', value: 'MOP' },
  { id: 90, symbol: 'MKD', value: 'MKD.ден', label: 'Macedonian Denar' },
  { id: 91, symbol: 'MGA', label: 'Malagasy Ariary', value: 'MGA' },
  { id: 92, symbol: 'MWK', label: 'Malawian Kwacha', value: 'MWK' },
  { id: 93, symbol: 'MYR', value: 'MYR.RM', label: 'Malaysian Ringgit' },
  { id: 94, symbol: 'MVR', label: 'Maldivian Rufiyaa', value: 'MVR' },
  { id: 95, symbol: 'MRO', label: 'Mauritanian Ouguiya', value: 'MRO' },
  { id: 96, symbol: 'MUR', value: 'MUR.Rs', label: 'Mauritian Rupee' },
  { id: 97, symbol: 'MXN', value: 'MXN.$', label: 'Mexican Peso' },
  { id: 98, symbol: 'MDL', label: 'Moldovan Leu', value: 'MDL' },
  { id: 99, symbol: 'MNT', value: 'MNT.₮', label: 'Mongolian Tugrik' },
  { id: 100, symbol: 'MAD', label: 'Moroccan Dirham' },
  { id: 101, symbol: 'MZM', value: 'MZM.MT', label: 'Mozambican Metical' },
  { id: 102, symbol: 'MMK', label: 'Myanmar Kyat', value: 'MMK' },
  { id: 103, symbol: 'NAD', value: 'NAD.$', label: 'Namibian Dollar' },
  { id: 104, symbol: 'NPR', value: 'NPR.Rs', label: 'Nepalese Rupee' },
  {
    id: 105,
    symbol: 'ANG',
    value: 'ANG.ƒ',
    label: 'Netherlands Antillean Guilder',
  },
  { id: 106, symbol: 'TWD', value: 'TWD.NT$', label: 'New Taiwan Dollar' },
  { id: 107, symbol: 'NZD', value: 'NZD.$', label: 'New Zealand Dollar' },
  { id: 108, symbol: 'NIO', value: 'NIO.C$', label: 'Nicaraguan CÃ³rdoba' },
  { id: 109, symbol: 'NGN', value: 'NGN.₦', label: 'Nigerian Naira' },
  { id: 110, symbol: 'KPW', value: 'KPW.₩', label: 'North Korean Won' },
  { id: 111, symbol: 'NOK', value: 'NOK.kr', label: 'Norwegian Krone' },
  { id: 112, symbol: 'OMR', label: 'Omani Rial', value: 'OMR' },
  { id: 113, symbol: 'PKR', value: 'PKR.Rs', label: 'Pakistani Rupee' },
  { id: 114, symbol: 'PAB', value: 'PAB.B/.', label: 'Panamanian Balboa' },
  { id: 115, symbol: 'PGK', label: 'Papua New Guinean Kina', value: 'PGK' },
  { id: 116, symbol: 'PYG', value: 'PYG.Gs', label: 'Paraguayan Guarani' },
  { id: 117, symbol: 'PEN', value: 'PEN.S/.', label: 'Peruvian Nuevo Sol' },
  { id: 118, symbol: 'PHP', value: 'PHP.₱', label: 'Philippine Peso' },
  { id: 119, symbol: 'PLN', value: 'PLN.zł', label: 'Polish Zloty' },
  { id: 120, symbol: 'QAR', label: 'Qatari Rial', value: 'QAR' },
  { id: 121, symbol: 'RON', value: 'RON.lei', label: 'Romanian Leu' },
  { id: 122, symbol: 'RUB', value: 'RUB.₽', label: 'Russian Ruble' },
  { id: 123, symbol: 'RWF', label: 'Rwandan Franc', value: 'RWF' },
  { id: 124, symbol: 'SVC', value: 'SVC.$', label: 'Salvadoran ColÃ³n' },
  { id: 125, symbol: 'WST', label: 'Samoan Tala', value: 'WST' },
  { id: 126, symbol: 'SAR', label: 'Saudi Riyal', value: 'SAR' },
  { id: 127, symbol: 'RSD', value: 'RSD.Дин.', label: 'Serbian Dinar' },
  { id: 128, symbol: 'SCR', value: 'SCR.Rs', label: 'Seychellois Rupee' },
  { id: 129, symbol: 'SLL', label: 'Sierra Leonean Leone', value: 'SLL' },
  { id: 130, symbol: 'SGD', value: 'SGD.$', label: 'Singapore Dollar' },
  { id: 131, symbol: 'SKK', label: 'Slovak Koruna', value: 'SKK' },
  { id: 132, symbol: 'SBD', value: 'SBD.$', label: 'Solomon Islands Dollar' },
  { id: 133, symbol: 'SOS', value: 'SOS.S', label: 'Somali Shilling' },
  { id: 134, symbol: 'ZAR', value: 'ZAR.R', label: 'South African Rand' },
  { id: 135, symbol: 'KRW', value: 'KRW.₩', label: 'South Korean Won' },
  { id: 136, symbol: 'XDR', label: 'Special Drawing Rights', value: 'XDR' },
  { id: 137, symbol: 'LKR', value: 'LKR.Rs', label: 'Srilankan Rupee' },
  { id: 138, symbol: 'SHP', value: 'SHP.£', label: 'St. Helena Pound' },
  { id: 139, symbol: 'SDG', label: 'Sudanese Pound', value: 'SDG' },
  { id: 140, symbol: 'SRD', value: 'SRD.$', label: 'Surinamese Dollar' },
  { id: 141, symbol: 'SZL', label: 'Swazi Lilangeni', value: 'SZL' },
  { id: 142, symbol: 'SEK', value: 'SEK.kr', label: 'Swedish Krona' },
  { id: 143, symbol: 'CHF', value: 'CHF', label: 'Swiss Franc' },
  { id: 144, symbol: 'SYP', value: 'SYP.£', label: 'Syrian Pound' },
  {
    id: 145,
    symbol: 'STD',
    label: 'São Tomé and Príncipe Dobra',
    value: 'STD',
  },
  { id: 146, symbol: 'TJS', label: 'Tajikistani Somoni', value: 'TJS' },
  { id: 147, symbol: 'TZS', label: 'Tanzanian Shilling', value: 'TZS' },
  { id: 148, symbol: 'THB', value: 'THB.฿', label: 'Thai Baht' },
  { id: 149, symbol: 'TOP', label: 'Tongan paanga', value: 'TOP' },
  {
    id: 150,
    symbol: 'TTD',
    value: '93.TT$',
    label: 'Trinidad & Tobago Dollar',
  },
  { id: 151, symbol: 'TND', label: 'Tunisian Dinar', value: 'TND' },
  {
    id: 152,
    symbol: 'TRY',
    value: '94.₺',
    label: 'Turkish Lira',
  },
  { id: 153, symbol: 'TMT', label: 'Turkmenistani Manat', value: 'TMT' },
  { id: 154, symbol: 'UGX', label: 'Ugandan Shilling', value: 'UGX' },
  { id: 155, symbol: 'UAH', value: '95.₴', label: 'Ukrainian Hryvnia' },
  {
    id: 156,
    symbol: 'AED',
    label: 'United Arab Emirates Dirham',
    value: 'AED',
  },
  { id: 157, symbol: 'UYU', value: '96.$U', label: 'Uruguayan Peso' },
  { id: 158, symbol: 'AFA', label: 'Afghan Afghani', value: 'AFA' },
  { id: 159, symbol: 'UZS', value: '98.лв', label: 'Uzbekistan Som' },
  { id: 160, symbol: 'VUV', label: 'Vanuatu Vatu', value: 'VUV' },
  { id: 161, symbol: 'VEF', value: '99.Bs', label: 'Venezuelan BolÃ­var' },
  { id: 162, symbol: 'VND', value: '100.₫', label: 'Vietnamese Dong' },
  { id: 163, symbol: 'YER', label: 'Yemeni Rial', value: 'YER' },
  { id: 164, symbol: 'ZMD', value: '101.Z$', label: 'Zimbabwe Dollar' },
];

export default currencies;
