const timezones = [
  {
    index: 1,
    value: 'Pacific/Midway',
    label: 'Midway Island, Samoa (GMT-11:00)',
  },
  { index: 2, value: 'Pacific/Honolulu', label: 'Hawaii (GMT-10:00)' },
  { index: 3, value: 'America/Juneau', label: 'Alaska (GMT-8:00)' },
  { index: 4, value: 'America/California', label: 'California (GMT-7:00)' },
  { index: 5, value: 'America/Dawson', label: 'Dawson, Yukon (GMT-7:00)' },
  { index: 6, value: 'America/Phoenix', label: 'Arizona (GMT-7:00)' },
  {
    index: 7,
    value: 'America/Tijuana',
    label: 'Tijuana, Pacific Time (GMT-7:00)',
  },
  { index: 8, value: 'America/Boise', label: 'Mountain Time (GMT-6:00)' },
  {
    index: 9,
    value: 'America/Chihuahua',
    label: 'Chihuahua, La Paz, Mazatlan (GMT-6:00)',
  },
  { index: 10, value: 'America/Regina', label: 'Saskatchewan (GMT-6:00)' },
  { index: 11, value: 'America/Belize', label: 'Central America (GMT-6:00)' },
  { index: 12, value: 'America/Chicago', label: 'Central Time (GMT-5:00)' },
  {
    index: 13,
    value: 'America/Mexico_City',
    label: 'Guadalajara, Mexico City, Monterrey (GMT-5:00)',
  },
  {
    index: 14,
    value: 'America/Bogota',
    label: 'Bogota, Lima, Quito (GMT-5:00)',
  },
  { index: 15, value: 'America/Detroit', label: 'Eastern Time (GMT-4:00)' },
  { index: 16, value: 'America/Caracas', label: 'Caracas, La Paz (GMT-4:00)' },
  { index: 17, value: 'America/Santiago', label: 'Santiago (GMT-4:00)' },
  { index: 18, value: 'America/Sao_Paulo', label: 'Brasilia (GMT-3:00)' },
  {
    index: 19,
    value: 'America/Argentina/Buenos_Aires',
    label: 'Buenos Aires, Georgetown (GMT-3:00)',
  },
  {
    index: 20,
    value: 'America/St_Johns',
    label: 'Newfoundland and Labrador (GMT-2:30)',
  },
  { index: 21, value: 'America/Godthab', label: 'Greenland (GMT-2:00)' },
  {
    index: 22,
    value: 'Atlantic/Cape_Verde',
    label: 'Cape Verde Islands (GMT-1:00)',
  },
  { index: 23, value: 'Atlantic/Azores', label: 'Azores (GMT+0:00)' },
  { index: 24, value: 'GMT', label: 'UTC (GMT+0:00)' },
  {
    index: 25,
    value: 'Africa/Casablanca',
    label: 'Casablanca, Monrovia (GMT+0:00)',
  },
  { index: 26, value: 'Europe/London', label: 'Edinburgh, London (GMT+1:00)' },
  { index: 27, value: 'Europe/Dublin', label: 'Dublin (GMT+1:00)' },
  { index: 28, value: 'Europe/Lisbon', label: 'Lisbon (GMT+1:00)' },
  { index: 29, value: 'Atlantic/Canary', label: 'Canary Islands (GMT+1:00)' },
  {
    index: 30,
    value: 'Africa/Algiers',
    label: 'West Central Africa (GMT+1:00)',
  },
  {
    index: 31,
    value: 'Europe/Belgrade',
    label: 'Belgrade, Bratislava, Budapest, Ljubljana, Prague (GMT+2:00)',
  },
  {
    index: 32,
    value: 'Europe/Sarajevo',
    label: 'Sarajevo, Skopje, Warsaw, Zagreb (GMT+2:00)',
  },
  {
    index: 33,
    value: 'Europe/Brussels',
    label: 'Brussels, Copenhagen, Madrid, Paris (GMT+2:00)',
  },
  {
    index: 34,
    value: 'Europe/Amsterdam',
    label: 'Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna (GMT+2:00)',
  },
  { index: 35, value: 'Africa/Cairo', label: 'Cairo (GMT+2:00)' },
  { index: 36, value: 'Africa/Harare', label: 'Harare, Pretoria (GMT+2:00)' },
  { index: 37, value: 'Europe/Bucharest', label: 'Bucharest (GMT+3:00)' },
  {
    index: 38,
    value: 'Europe/Helsinki',
    label: 'Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius (GMT+3:00)',
  },
  {
    index: 39,
    value: 'Europe/Athens',
    label: 'Athens, Istanbul, Minsk (GMT+3:00)',
  },
  { index: 40, value: 'Asia/Jerusalem', label: 'Jerusalem (GMT+3:00)' },
  {
    index: 41,
    value: 'Europe/Moscow',
    label: 'Moscow, St. Petersburg, Volgograd (GMT+3:00)',
  },
  { index: 42, value: 'Asia/Kuwait', label: 'Kuwait, Riyadh (GMT+3:00)' },
  { index: 43, value: 'Africa/Nairobi', label: 'Nairobi (GMT+3:00)' },
  { index: 44, value: 'Asia/Baghdad', label: 'Baghdad (GMT+3:00)' },
  { index: 45, value: 'Asia/Dubai', label: 'Abu Dhabi, Muscat (GMT+4:00)' },
  { index: 46, value: 'Asia/Tehran', label: 'Tehran (GMT+4:30)' },
  { index: 47, value: 'Asia/Kabul', label: 'Kabul (GMT+4:30)' },
  { index: 48, value: 'Asia/Baku', label: 'Baku, Tbilisi, Yerevan (GMT+5:00)' },
  { index: 49, value: 'Asia/Yekaterinburg', label: 'Ekaterinburg (GMT+5:00)' },
  {
    index: 50,
    value: 'Asia/Karachi',
    label: 'Islamabad, Karachi, Tashkent (GMT+5:00)',
  },
  {
    index: 51,
    value: 'Asia/Kolkata',
    label: 'Chennai, Kolkata, Mumbai, New Delhi (GMT+5:30)',
  },
  { index: 52, value: 'Asia/Colombo', label: 'Sri Jayawardenepura (GMT+5:30)' },
  { index: 53, value: 'Asia/Kathmandu', label: 'Kathmandu (GMT+5:45)' },
  { index: 54, value: 'Asia/Dhaka', label: 'Astana, Dhaka (GMT+6:00)' },
  { index: 55, value: 'Asia/Almaty', label: 'Almaty, Novosibirsk (GMT+6:00)' },
  { index: 56, value: 'Asia/Rangoon', label: 'Yangon Rangoon (GMT+6:30)' },
  {
    index: 57,
    value: 'Asia/Bangkok',
    label: 'Bangkok, Hanoi, Jakarta (GMT+7:00)',
  },
  { index: 58, value: 'Asia/Krasnoyarsk', label: 'Krasnoyarsk (GMT+7:00)' },
  {
    index: 59,
    value: 'Asia/Shanghai',
    label: 'Beijing, Chongqing, Hong Kong SAR, Urumqi (GMT+8:00)',
  },
  {
    index: 60,
    value: 'Asia/Kuala_Lumpur',
    label: 'Kuala Lumpur, Singapore (GMT+8:00)',
  },
  { index: 61, value: 'Asia/Taipei', label: 'Taipei (GMT+8:00)' },
  { index: 62, value: 'Australia/Perth', label: 'Perth (GMT+8:00)' },
  {
    index: 63,
    value: 'Asia/Irkutsk',
    label: 'Irkutsk, Ulaanbaatar (GMT+8:00)',
  },
  { index: 64, value: 'Asia/Seoul', label: 'Seoul (GMT+9:00)' },
  { index: 65, value: 'Asia/Tokyo', label: 'Osaka, Sapporo, Tokyo (GMT+9:00)' },
  { index: 66, value: 'Australia/Darwin', label: 'Darwin (GMT+9:30)' },
  { index: 67, value: 'Australia/Adelaide', label: 'Adelaide (GMT+9:30)' },
  { index: 68, value: 'Asia/Yakutsk', label: 'Yakutsk (GMT+10:00)' },
  {
    index: 69,
    value: 'Australia/Sydney',
    label: 'Canberra, Melbourne, Sydney (GMT+10:00)',
  },
  { index: 70, value: 'Australia/Brisbane', label: 'Brisbane (GMT+10:00)' },
  { index: 71, value: 'Australia/Hobart', label: 'Hobart (GMT+10:00)' },
  { index: 72, value: 'Asia/Vladivostok', label: 'Vladivostok (GMT+10:00)' },
  { index: 73, value: 'Pacific/Guam', label: 'Guam, Port Moresby (GMT+10:00)' },
  {
    index: 74,
    value: 'Asia/Magadan',
    label: 'Magadan, Solomon Islands, New Caledonia (GMT+11:00)',
  },
  {
    index: 75,
    value: 'Asia/Kamchatka',
    label: 'Kamchatka, Marshall Islands (GMT+12:00)',
  },
  { index: 76, value: 'Pacific/Fiji', label: 'Fiji Islands (GMT+12:00)' },
  {
    index: 77,
    value: 'Pacific/Auckland',
    label: 'Auckland, Wellington (GMT+12:00)',
  },
  { index: 78, value: 'Pacific/Tongatapu', label: "Nuku'alofa (GMT+13:00)" },
];

export default timezones;
